name: tefis_tool
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.1+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  dartssh2: ^2.8.2
  flutter:
    sdk: flutter
  local_auth: ^2.1.6
  path: ^1.8.2
  rename: ^2.1.1
  shared_preferences: ^2.1.0
  sqflite: ^2.2.6
  toast: ^0.3.0
  xterm: ^3.4.1
dev_dependencies:
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path_android: "assets/launcher.png"
  image_path_ios: "assets/launcher.png"
  android: true
  ios: true
flutter:
  uses-material-design: true